package com.ajcordenete.network

const val BASE_URL = "https://jsonplaceholder.typicode.com"
const val API = "api"
const val VERSION = "v1"
const val ENDPOINT_FORMAT = "%s/%s/%s/"

const val HTTP_UNPROCESSABLE_ENTITY = 422

const val IO_EXCEPTION = "IO_EXCEPTION"

// Error codes
const val ERROR_USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND"
const val ERROR_AUTHENTICATION_EMAIL_REQUIRED = "AUTHENTICATION_EMAIL_REQUIRED"
const val ERROR_AUTHENTICATION_PHONE_NUMBER_REQUIRED = "AUTHENTICATION_PHONE_NUMBER_REQUIRED"
const val ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"